### PR TITLE
New settings, context menu, and performance improvements

### PR DESCRIPTION
**Pull request by Mbucari**
## [improve startup time](https://github.com/rmcrackan/Libation/commit/5d5e3a6671ab72db426dd079a1e26e8cf69a257a)

- Begin loading the library as soon as possible. I've been doing this in chardonnay since day 1 to speed up startup times.
- Use the initially loaded library to set backup counts
- Parallelize GridEntry creation

All in, Libation loads about 30% faster with my library.

##  [Add full context menu to call columns](https://github.com/rmcrackan/Libation/commit/932472cb91ddcd83d9e8ced28d77fea7a9107a26)

As discussed in #662

## [Add new settings and settings dialog help tips](https://github.com/rmcrackan/Libation/commit/4899ef300745e8e0e78848ed17a88685ddbfc9f6)

- Add CombineNestedChapterTitles setting (#663)
- Add SaveMetadataToFile setting (@wtanksleyjr has been salivating for this)
- Add extended setting descriptions for select options. Additional help text displayed on mouseover for some of the more opaque settings.

## [Add Re-download context menu item](https://github.com/rmcrackan/Libation/commit/7d09728e6bd4cdd65664a93fb83dfb05c6ac2dbf)

Suggested by @CLHatch in #662

### CODE REVIEW

**Comment by rmcrackan** [comment]
I'm a bit tired to give this appropriate attention tonight. At a glance I like what I see.

**Comment by Mbucari** [comment]
> I'm a bit tired to give this appropriate attention tonight. At a glance I like what I see.

No worries.

One thing I recently discovered is that when there's an active PR you can select the PR branch in visual studio and view/debug all the changes locally.

**Comment by rmcrackan** [comment]
I can't mentally parse all the little details in "Add full context menu to call columns" -- what's the gist?

**Comment by rmcrackan** [comment]
> Add SaveMetadataToFile setting (@wtanksleyjr has been salivating for this)

LOL

**Comment by rmcrackan** [comment]
You caught me in the nick of time. I was just about to start the release. I'll hold off.

**Comment by rmcrackan** [comment]
I think we need to change the re-download. I downloaded a book the normal way. Move the folder to somewhere still find-able by Libation. asin is still in the dir and file names. Do a re-download via the new context menu item. The new version is created in the default location; not in the folder with asin. I'd expected the latter.

**Comment by CLHatch** [comment]
> I think we need to change the re-download. I downloaded a book the normal way. Move the folder to somewhere still find-able by Libation. asin is still in the dir and file names. Do a re-download via the new context menu item. The new version is created in the default location; not in the folder with asin. I'd expected the latter.

I was wondering if that would be an issue.  It always uses the renaming pattern, right?

**Comment by rmcrackan** [comment]
> It always uses the renaming pattern, right?

Weeeeeeell shit. Yeah. That makes sense. Hmmm. Not sure how to resolve this incongruity....

**Comment by CLHatch** [comment]
> > It always uses the renaming pattern, right?
> 
> Weeeeeeell shit. Yeah. That makes sense. Hmmm. Not sure how to resolve this incongruity....

Two options when doing a re-download?  One ignoring t he "folder" renaming, one using it?

**Pull request merged**
