### PR TITLE
Option to combine Opening/End Credits chapters and other changes

### PR DESCRIPTION
**Pull request by Mbucari**
- Added a new user audio setting to merge Opening and End Credits chapters with the following/preceding chapter. I also added more chapter tests.
- Added audio bitrate to the database.  I added it as an enum type, `AudioFormatEnum`, that stores bitrate, sample rate, and channel configuration.  `AudioFormatEnum` is internal to DataLayer, and is exposed to referencing assemblies inside `AudioFormat `, which displays the info in a much more friendly way.  `AudioFormatEnum` enum value names match the `AvailableCodec.EnhancedCodec` names, allowing them to be parsed from strings.  The bitrate info is displayed in the `BookDetailsDialog`, but nowhere else yet.
- Configured libation to build via publish.
  -  To do this, I had to get rid of MSBUMP.  It would work, but after cleaning the solution `dotnet publish` would fail.  I replaced it with a dotnet tool: [frogvall.dotnetbumpversion](https://www.nuget.org/packages/Frogvall.DotnetBumpVersion/).  A pre-bild command will increment the build version, but only for debug builds. That way you can publish all 3 Libation exe files without AppScaffolding's build being incremented each time.
  - Added FolderPublish config files for all 3 libation exe's.
  - Added publish.ps1to the Source dir.  To publish, all you have to do is open the dev console and type `.\publish`.  The script will build all files and zip them to \\Source\\bin\\Libation.[ver].zip
    - NOTE: to run powershell scripts you need to enable script execution.  Run this command to enable: 
    - `Set-ExecutionPolicy -Scope CurrentUser Unrestricted`

### CODE REVIEW

**Comment by Mbucari** [comment]
I'm working on #301

**Comment by Mbucari** [comment]
I've fixed #201, but it does require that change to AudibleApi.Common in my email.

**Comment by rmcrackan** [comment]
the emailed change to audibleapi.common/audibleapi is now live. AudibleUtiliies is updated

**Comment by Mbucari** [comment]
Updated package reference

**Pull request merged**
