### PR TITLE
Batch of Fixxed Issues

### PR DESCRIPTION
**Pull request by Mbucari**
## [Add custom column widths to chardonnay](https://github.com/rmcrackan/Libation/commit/97f94d8782ddd12dbf1b73f33e45970c416afec2)

Chardonnay users can now manually resize their grid columns. This only became possible in 11.0.1, and it's something I've wanted to do for a while. (I mean, OK, it technically _was_ possible before. But now it's possible without a ton of hacks)

## [Lazy load cover to improve startup time](https://github.com/rmcrackan/Libation/commit/893d68190dfb187d30ecde174d53868ff8c605e9)

If I could turn back time I would have just done this instead of parallelizing grid loading. Loading images into the GUI renderer is far and away the most costly part of creating the grid.

Also some slight refactoring.

## [Fix MessageBox crash when UI has no Screens](https://github.com/rmcrackan/Libation/commit/ff3ac2d6fd23291e940ccb7231814f074f34b6d5) (#708)

Not sure why that error is happening, but this should prevent a crash.

## [Add ability to preview templates on user's books](https://github.com/rmcrackan/Libation/commit/e65b6c76a8d27b4286c03d23e293f4d4b78fd6fa) (#700)

This is pretty cool. There's a new grid context menu item for editing templates using the clicked book as the preview.

## [Update audio duration on library scan](https://github.com/rmcrackan/Libation/commit/fb9b4eb77e9f34275569851ed86522c4368a0343) (#707)

### CODE REVIEW

**Comment by rmcrackan** [comment]
First of all, thank you again for however it is that you've segregated and linked the features. That makes it SO easy to review. The only thing I couldn't easily review via code-surfing was the template preview so I cloned your repo to see it live. That is indeed slick.

My only minor concern is about user expectation. It could be perceived that the user can use your new context option to save a filter *for that book* (as opposed to globally). To take that to it's conclusion, what happens when they say: I'd like a way to do that. My inclination is to politely decline that request. Just be prepared for it.

Again: nice work. Do you think this should be another incremental upgrade or are we ready for ver. 11? If 11, I'll make a large announcement on reddit. Note: this usually brings in a fair number of new users and/or upgraders so if we (read: you) aren't confident in the stability of recent upgrades then we're better off doing an incremental release and letting these recent changes get some more time in the wild. Your call. There have been a lot of great improvements lately. Well done!

**Comment by CLHatch** [comment]
> > My only minor concern is about user expectation. It could be perceived that the user can use your new context option to save a filter for that book (as opposed to globally)
> 
> I had that same thought right at the end as I was finishing up the feature. "Politely declining" was also my plan 😂
> 
So what I hear you saying is that the next major feature you are working on is saving filters for books? :-P

**Comment by rmcrackan** [comment]
> So what I hear you saying is that the next major feature you are working on is saving filters for books?

[Found this for you](https://www.google.com/search?q=hearing+test+near+me)

**Comment by CLHatch** [comment]
> I like the idea of version 11. I don't really have any big new ideas in mind right now, so might as well push it. We've been in bug fix mode with very few new features for the last few months, so I've got a lot of confidence in Libations stability right now. I also feel good about everything in this PR.

I installed v11 as soon as it went up, and so far no issues on my end. Looking good! :)

**Comment by rmcrackan** [comment]
> I installed v11 as soon as it went up, and so far no issues on my end. Looking good! :)

w00h00! Thanks for letting me know :)

**Comment by CLHatch** [comment]
> > I installed v11 as soon as it went up, and so far no issues on my end. Looking good! :)
> 
> w00h00! Thanks for letting me know :)

Pretty good odds I'm the first to install it other than the two of you. :-D  Saw the email notification, and grabbed it immediately.

**Comment by rmcrackan** [comment]
> Pretty good odds I'm the first to install it other than the two of you

No doubt. I think you're spot on

**Comment by Mbucari** [comment]
Hopefully v11.0.0 lasts longer than V10.0.0. That one didn't even last to the following calendar day.

**Comment by rmcrackan** [comment]
> Hopefully v11.0.0 lasts longer than V10.0.0. That one didn't even last to the following calendar day.

lol you're not wrong. Bugs happen tho -- nature of the beast. We're all just writing tomorrow's obsolete code

**Pull request merged**
