### PR TITLE
Lots of Bug Fixes and 2 New Features.

### PR DESCRIPTION
**Pull request by Mbucari**
## [When book is unavailable, check other accounts](https://github.com/rmcrackan/Libation/commit/fd16e97632578c210a435039789c76272a556d9e) (#535)

When importing, use the new `ToDictionarySafe` method that accepts a tiebreaker delegate. The tiebreaker accepts two `ImportItem` and returns the winner. The first `ImportItem ` is always returned unless it is unavailable and the second is available. An example of this working is you have two accounts, [Account A] and [Account B] with [Book]. Libation already imported [Book] under [Account A], but then you returned it on that account. On the next scan, the importer notices that [Book] is unavailable on [Account A] and that it is still available on [Account B], so it updates the `LibraryBook` with [Account B].

## [Preserve "expanded" status when updating library](https://github.com/rmcrackan/Libation/commit/56de1e7659f6c44636429ac41d0ebb09f79b885c)

Fixed an issue when after a scan, all podcasts would expand again.

## [Suppress VisibleCountChanged firing when updating grid](https://github.com/rmcrackan/Libation/commit/2725340994228428a3ad39175a15b5f3dadb8fe8)

When a scan added many books, the UI was being bogged down because `VisibleCountChanged` was being fired after every entry was added.

## [Add series # to grid display](https://github.com/rmcrackan/Libation/commit/565c84c4ab4f693882677b958c61d35b3c794b25) (#529)

This is just the series number in parentheses after the name in the series column. I'll work on adding a separate column later.

## [Create books directory if not found](https://github.com/rmcrackan/Libation/commit/99687e968e81f8f945d05b7637b3f55bd1752220) (#542)

I also had to fix this commit here: [Fix SettingsFileIsValid](https://github.com/rmcrackan/Libation/commit/ed6f741a659f340c22759e97b1417136d0a219ac)

## [Add context menu to Series grid entries](https://github.com/rmcrackan/Libation/commit/784ab73a36a6c979610bfb72adee4e491f48fa91) (#536)

Series expand/collapse buttons have a full context menu now. I also moved the WinForms context menu into `ProductsDisplay`

## [Add SeriesViewDialog](https://github.com/rmcrackan/Libation/commit/9ae1f0399b871cffa5751184d65ea22a10463701)

This is the first Shiny New Thing (TM). Added a new context menu item to view all books/episodes in a series. If a Book/Episode is Ayce, provide a button to add/remove it from the Library. If it's not Ayce, the button adds/removes it from the wish list.

## [Log DTO items even if validation fails](https://github.com/rmcrackan/Libation/commit/e7eac7bed33be949e0de1be5962fa6ba4a324ba1)

This was a problem in #543. I couldn't get the DTOs causing the problem because the exception prevented them from being written.

## [Ensure series and episode DateAdded is never default](https://github.com/rmcrackan/Libation/commit/1783da3e2d59d335229950f7839ebae5bce63645) (#545 and #547)

I THINK this solves the issue, but I never got confirmation from either of the OPs

## [Migrate to Avalonia 11.0.0-preview6](https://github.com/rmcrackan/Libation/commit/7289459170b33774781200e298d8c034d996c227)

Preview 6 probably has all of the v11 breaking changes. It makes themes a lot easier, the deploy builds are smaller, startup times are faster, and general performance improvements.

One caveat: I can no longer run it on macOS VM. [I opened an issue about it](https://github.com/AvaloniaUI/Avalonia/issues/10770), but the dev team doesn't seem concerned about it not working on a mac VM. (Also, it's pretty ironic for a Muscovite to be commenting on software licensing violations.)

## [Add dark mode support](https://github.com/rmcrackan/Libation/commit/fc6f494f0d8a385ae192c3dd76d37316ae467dbc) (#497)

The second Shiny New Thing. This looks SLICK. You have to run it to see it. It's my new favorite mode.

I made all icons vector graphics, so their colors can be changed by editing their values in App.xaml.

### CODE REVIEW

**Comment by rmcrackan** [comment]
This looks great. I'd love to say I poured over every line but -- yeah, no. I browsed and it looked very good. I dig your summary above. Are all listed tickets ready to be closed? I also intend to research how to let you do that part without my intervention if you desire.

> Shiny New Thing (TM)

lol

> the dev team doesn't seem concerned about it not working on a mac VM

Dude, they literally don't have anything to offer if they aren't x-plat. What *are* they concerned with???

> Muscovite

? Not familiar with this term

> Add dark mode support

This mainly looks like avalonia. Does it work in winforms too?

-------

This is major enough that we're probably close to a new major version. Maybe a few extras (like #510 ) and if you had any 'high graphic impact, low functionality impact' tweaks that you wanted to do (as you did with dark mode), this could be a convenient time. tbh I've been looking forward to v10 for a long time. There's something special about that particular milestone.

I'd love to release v10 with a new website for getlibation.com. I have no design skills though and no one with those skills has been interested in contributing; so here we are. Oh well, the app's the thing and it's come a LONG damn way over the last year or so.

At one company, I'd been making *major* improvements for over a year. Later I changed the color scheme, the logo, and incremented the major version (for the first time in ages) and people acted like I hung the moon. I didn't feel like a fraud though because I really had created a much better product -- only it was slowly over a year and not when it went from yellow to blue.

**Comment by rmcrackan** [comment]
I invited you as a "collaborator." It'd be nice to still review your PRs -- I believe that's no longer a technical restriction though.

I'm also going to create a bunk issue. See if you can close and/or delete it.

**Comment by Mbucari** [comment]
> Are all listed tickets ready to be closed?

All except #529. I'll add the separate column for series number. I think I'll change the defauly settings so it's hidden by default.

> I also intend to research how to let you do that part without my intervention if you desire.

That'd be great!


> Dude, they literally don't have anything to offer if they aren't x-plat. What _are_ they concerned with???

I think maybe just that first dev was not concerned. Another dev changed the issue title, and it appears the problem is caused by macOS not having a graphics card attached. That's true in the VM because it can't talk to my graphics card so everything is software rendered, but that should never happen for any user with a real mac. (I hope. I really, really hope.)
 
> ? Not familiar with this term

Person from Moscow, Russia. It's where his profile says he's from. After they started their war and the world started sanctioning them, Russia essentially legalized piracy for IP of countries that sanctioned them. And even before that, Russians have always been strong players in the piracy scene.

> This mainly looks like avalonia. Does it work in winforms too?

No, it doesn't. Winforms just isn't built for theming. You'd have to change the colors on every single control, and that would get you only ~90% of the way there. Then there's all the accent colors within controls that wouldn't look right, and you'd probably only get at those through reflection.


> This is major enough that we're probably close to a new major version.

Agreed.

> Maybe a few extras (like #510 ) and if you had any 'high graphic impact, low functionality impact' tweaks that you wanted to do (as you did with dark mode), this could be a convenient time.

I'd like to finish up #529. And yes, I'd also like to rejigger the setup. I need to refactor Chardonnay's startup routine. It's a hacked together mess that I can barely understand.

Another thing I'd like to do is update the documentation. Go through it start to finish, add documentation for features that are missing delete anything that's no longer true.

> I'd love to release v10 with a new website for getlibation.com.

I think maybe a few screenshots of the updated UI would go a long way towards improving the look.

**Comment by Mbucari** [comment]
> It'd be nice to still review your PRs -- I believe that's no longer a technical restriction though.

Absolutely. I really don't want the pressure of being the only set of eyes on it before it's released lol.

**Comment by rmcrackan** [comment]
Totally agree about Russia and piracy. It never occurred to me to wonder what someone from Moscow was called though. Learn something new every day.

> dark mode ... Winforms

I assumed that was the case. I remember doing just 1 new theme once in Winforms and it was brutal. Pretty appropriate: want screen-reading for visually impared users? winforms. Better visuals for non-impared: avalonia

> documentation

Hey, just what are you trying to say about my insanely out of date documentation which was never great to begin with?!

**Pull request merged**
