### PR TITLE
Fix NRE when item has no category ladders (#715)

### PR DESCRIPTION
**Pull request by Mbucari**
This should be released asap because it's preventing the user from importing his library.

### CODE REVIEW

**Comment by rmcrackan** [comment]
On it

**Comment by Mbucari** [comment]
All-in-all a pretty good record for v11.0.0! It survived nearly a week and is only being replaced because of a bug from a much earlier release.

**Comment by CLHatch** [comment]
> All-in-all a pretty good record for v11.0.0! It survived nearly a week and is only being replaced because of a bug from a much earlier release.

Alas, v11.0.0... We knew him well.

**Comment by rmcrackan** [comment]
Agreed. I'm pleased. New version building now

**Comment by rmcrackan** [comment]
In case you're wondering, github only gives me a few concurrent build actions at a time, so I often cancel some of the automatic runs to rush the version built to the top of the queue.

**Pull request merged**
