### PR TITLE
Improve library scan speed and Track and display book availability

### LINKED ISSUE #523: VISIBLE 0 BOOKS
**Describe the bug**
I HAVE MANY BOOKS BUT AFTER NEW UPDATE IT SHOW VISIBLE 0 BOOK
Screenshot 2023-03-05 165128
Screenshot 2023-03-05 165128

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

### PR DESCRIPTION
**Pull request by Mbucari**
Again, changes are broken up by commits (except for "Improve library scan performance" which is split in half because I forgot to pull in a merge).

# [Add last downloaded info to exports](https://github.com/rmcrackan/Libation/commit/cdb27ef712d7e23cace8d885dac27c1a8ec16d73)

You'd asked for this in my last PR

# [Improve library scan performance](https://github.com/rmcrackan/Libation/pull/524/files#diff-86df73cf7abdd921714ff352ba3bb2279ca9909ecdb4357e47f3d5e7cb3d6aa1)

This change is split across 3 commits, but only [ApiExtended.cs](https://github.com/rmcrackan/Libation/pull/524/files#diff-86df73cf7abdd921714ff352ba3bb2279ca9909ecdb4357e47f3d5e7cb3d6aa1) was changed.

Episode fetching was poorly batched. All episodes of a series were fetched synchronously in the same Task, so some podcasts with hundreds of episodes would bog down the scan. Now, Episode retrieval is done in batches of no more than 50, dramatically increasing scan speeds for users with large podcasts (my library scan speed increased by 60%).

Also notice that MaxConcurrency has increased from 5 to 10. Actual max concurrency prior to this change was actually 15. That's because AudibleApi's library scan had a concurrency limit of 10, and Libation would simultaneously download episodes with a max concurrency of 5. Now, episode scanning only begins after the Api has completed scanning the library.

# [Add AbsentFromLastScan](https://github.com/rmcrackan/Libation/commit/f6dcc0db1db8fca42c76d42f288b5494ea54afd1)

I decided on `AbsentFromLastScan` instead of `PresentInLastScan` to maintain default behavior immediately after a user migrates (since  post-migration values will be default false).

# [Show AbsentFromLastScan book status in grid](https://github.com/rmcrackan/Libation/commit/3ebd4ce24381df4fa01e7716a6bea440dfa87700)

If a book (or pdf) is not liberated and `AbsentFromLastScan ` is true, the grid button does nothing and the button image is grayed. Additionally, these absent books are excluded from unliberated counts and are not queued for download.

Solved #269

# [Fix #523](https://github.com/rmcrackan/Libation/pull/524/commits/e76f99ff28bb8bc19f71ec87761061ec839f9bb1)

If cover art fails to load, load the default image instead.

### CODE REVIEW

**Comment by rmcrackan** [comment]
> Episode fetching was poorly batched

Good call. This is a nice evolution of the process.

**Comment by rmcrackan** [comment]
I like the broken out and linked commits. Very clean. Following those links, I added some comments on the commit level rather than the full PR level. Let me know if you don't get notified of them.

**Comment by rmcrackan** [comment]
Lookin good.

Regarding our other discussion on how to report unavailables: I'm fine with any reasonable choice as a first draft with the understanding that it could require tweaking if our way confuses users.

I'm good to merge after those 2 comments in "Add AbsentFromLastScan" are complete. No major issues.

**Comment by Mbucari** [comment]
> This is a nice evolution of the process.

Yeah, there's only 1 step after this: Write episode asins to a channel, read them in batches of 50 and spin up a new get request, then set series info after all episodes have been downloaded. It sounds messy, but I'm sure it can be made neat and readable with some careful thought.

> how to report unavailables

Hold off on this merge and I'll try adding unavailable books to the taskbar count. I still think not adding unavailable to the Liberate menu items counts is the right choice, but status bar is a good idea.

**Comment by rmcrackan** [comment]
> Hold off on this merge

Will do. Lemme know when you're ready. I'm quite happy with what I see.

**Comment by Mbucari** [comment]
OK, it's done. New "Unavailable" counts for both books and PDFs. If a book or pdf is AbsentFromLastScan but liberated, it's included in the liberated count and not in the Unavailable count.

**Comment by rmcrackan** [comment]
Verifying that this resolves #523 and #269 ?

**Comment by Mbucari** [comment]
> this resolves #523 and #269 ?

Yes indeedy.

**Comment by CharlieRussel** [comment]
Version 9.4.4 is noticeably faster returning from a scan. I didn't do any profiling, so can't quantify it, but I definitely noticed it after this latest install. Well Done!

**Pull request merged**
