### PR TITLE
Add some necessary files for the Flatpak

### PR DESCRIPTION
**Pull request by jwillikers**
Related to #810.

### CODE REVIEW

**Comment by rmcrackan** [comment]
Sorry for the delay. Is this PR ready for my approval? After this is done, what else do I need to do so the linux folks can benefit from it? This is all greek to me

**Comment by jwillikers** [comment]
> Sorry for the delay. Is this PR ready for my approval? After this is done, what else do I need to do so the linux folks can benefit from it? This is all greek to me

@rmcrackan I think it should be good. The only thing I haven't tested is the GitHub Actions, one of which will fail until this is merged. I set up the workflows to only run when the relevant files change, so even if I need to work out a kink, it shouldn't effect anyone else.

**Comment by rmcrackan** [comment]
Cool. Here goes nothing.

**Comment by jwillikers** [comment]
@rmcrackan I'll fix that

**Comment by rmcrackan** [comment]
Gracias

**Comment by rmcrackan** [comment]
included in https://github.com/rmcrackan/Libation/releases/tag/v11.5.4

**Pull request merged**
