### PR TITLE
About Dialog, mac menus, and hotkeys

### PR DESCRIPTION
**Pull request by Mbucari**
## [Add native menu for mac and refactor MainWindow](https://github.com/rmcrackan/Libation/commit/4a65d6bbd3faa9579193217fd29ecbebacfb5f70)

The majority of these changes were to move biz logic from `MainWindow` into its view model, `MainVM` (Previously named `MainWindow`). `MainVM` is still organized into multiple files, but the grouping is a little different than in classic. The whole reason for doind this is so I could use Avalonia's NativeMenus on macOS. Linux and Windows still use the original windowed menu, but macOS hides that menu and uses the OS's menu bar. Being native, customization is quite limited, so that menu is unhidden and used for the guided tour while the tour is running. All menu items are identical, so the point should be clear.

I've been meaning to refactor the view model for a while, and this was a good excuse.

## [Add About dialog](https://github.com/rmcrackan/Libation/commit/8d73f5cc7e0ee3e4b9bd587d00006c521335eda6)

Exactly as I showed in #534

## [UI Tweaks and new application hotkeys](https://github.com/rmcrackan/Libation/pull/565/commits/756d387238a06fab60dd6c7fc2bbfb8beef406a1)

Tweak the UI, and add application hotkeys to MainForm:

|Win/Linux|macOS|Action|
|-|-|-|
|ctrl+F|⌘+F|Focux the search filter textbox and select all text|
|ctrl+P|⌘+,|Settings|
|ctrl+shift+A|⌘+.|Accounts|
|F1 - F12|⌘+1 - ⌘+0|Apply nth Quick Filter|

## [Sort episodes by column beneath their parents](https://github.com/rmcrackan/Libation/pull/565/commits/2248d7b24eada32f8bec49853184f4c7b8562b3e)
[As discussed here](https://github.com/rmcrackan/Libation/issues/536#issuecomment-1483978394)

### CODE REVIEW

**Comment by Mbucari** [comment]
I updated the about dialog.
image

**Comment by rmcrackan** [comment]
Very cool. Minor suggestions

* I agree with CharlieRussel -- I'm not sure there's utility in showing loaded assemblies to users
* Please add your above shortcuts chart to the Mac's readme page

**Comment by Mbucari** [comment]
All right, how about this?
image

> add your above shortcuts chart to the Mac's readme page

There's no need. When you open the menu by clicking on it, you can see the shortcut key combinations for each menu item.

**Comment by rmcrackan** [comment]
Looks great for now and it will give us plenty of room to expand if needed. Goodbye shitty little messagebox with nothing but the version -- you'll not be missed.

**Comment by Mbucari** [comment]
Hold off on releasing this. IDK how this happened, but during my editing of the Winforms version somehow event handlers got removed from two controls.

**Comment by CharlieRussel** [comment]
Another thought that might be useful is a link/button to pull the logs and/or system information? Which could include details like which assemblies are loaded, what the underlying platform is, etc. And you could even have it zip them up to include with any bug report.

**Pull request merged**
