### PR TITLE
Minor Bug fixes

### PR DESCRIPTION
**Pull request by Mbucari**
## [Add support for locating mp3 audiobooks](https://github.com/rmcrackan/Libation/commit/92d283187df44243c09662da0d3f44e373d42999)

The "Locate Audiobooks" function will now locate mp3s.

## [Remove unused response groups](https://github.com/rmcrackan/Libation/commit/b405e8b6b242a093cfb3d6631941c718d35c1086)

This is just another step in trying to eek out another few milliseconds of performance from the library scan. I went through all response groups and removed the ones that provided unused data.

## [Add scrolling view to settings window panels](https://github.com/rmcrackan/Libation/commit/88c35e2a56ae340618bf7c48e4a9333298818425) (#720)

Chardonnay only. The tabs are placed inside a scroll viewer control so the window can be shrunk to smaller than the tab while still allowing all options to be accessed. I did only the most cursory search for a winforms equivalent but couldn't find one. Let me know if you have any ideas how we could add the same feature to classic.

## [Create directory before trying to create appsettings.json](https://github.com/rmcrackan/Libation/commit/f86c77a5463bc5585a42260e035710bfa78e415d)

Create the "Libation" subdirectory before trying to create appsettings.json. This only has the potential to affect mac and linux because windows should always be able to write to the libation program files directory.

## [Update AAXClean](https://github.com/rmcrackan/Libation/commit/42a93bfac17dbea3aa34aea105609bea6f7c9f1c)

There are a few things in here.
- AAXClean now properly writes track numbers to mp3 files split by chapter.
- Set the track number on the converted mp3 when _converting_ to mp3.
- Change how metadata is read from m4b files in the "Locate Audiobooks" process to improve performance.

## [Fix issue with save button being disabled.](https://github.com/rmcrackan/Libation/commit/e55e969349a56bb7fcbe0833c93e718641a1ca25)

This has been broken for a long time and I keep forgetting to fix it. When selecting "Returning User" in Libation setup on chardonnay, users were unable to save the selected directory.

## [Update InstallOnMac.md](https://github.com/rmcrackan/Libation/commit/49775b019c0193484d9add2a0abacc0009466ad3)

Add troubleshooting steps for mac users.

## [Add support for environment variables and unix shortcuts in appsettings.json path](https://github.com/rmcrackan/Libation/commit/d7f3758ebcbfce01bcc4017f589f74b85393a594)

.NET still has room for improvement to become truly cross-platform. IO can't interpret the home path (`~/`) shortcut, and `Environment.ExpandEnvironmentVariables()` only works for `%MyENV%` type environment variables, not unix's `$MyENV` variables. I added a hack for unix systems that calls the shell to echo the path name, thereby expanding it to it's full path. I only did this for `LibationFiles` directory in `appsettings.json` because I don't think it's needed anywhere else.

### CODE REVIEW

**Comment by rmcrackan** [comment]
> Let me know if you have any ideas how we could add the same feature to classic.

[Winforms panel with scrollbars](https://stackoverflow.com/a/730456)

> .NET still has room for improvement to become truly cross-platform

For sure. Win feels native and the others feel like a chore.

These look good to me. Ready for merge? Or would you like more time?

**Comment by rmcrackan** [comment]
Sounds good. Just reply here whenever you're ready.

**Comment by Mbucari** [comment]
@rmcrackan Dunzo. Thankfully `TabPage` inherits from `Panel` so I could just enable `AutoScroll` on each tab.

**Comment by Mbucari** [comment]
> Release today? Or do you have other things in the pipeline?

Yeah, please release this. I have some ideas for other open feature request issues, but I'm not quite ready to start working on them in earnest.

**Comment by Mbucari** [comment]
Holy crap, the [unix ExpandEnvironmentVariables issue](https://github.com/dotnet/runtime/issues/25792) has been open since 2018!

**Comment by rmcrackan** [comment]
Released

> Holy crap, the https://github.com/dotnet/runtime/issues/25792 has been open since 2018!

Like we said: Win feels native; mac and linux feel hacky.

**Pull request merged**
