### PR TITLE
Fix quick filter not being applied on startup

### PR DESCRIPTION
**Pull request by Mbucari**
Here's another minor one for you before you update Dinah.Core

### CODE REVIEW

**Comment by rmcrackan** [comment]
Ready for me to start the 10.6.2 build process?

**Comment by rmcrackan** [comment]
Oh yeah, and do you want me to reference any tickets in the release notes?

**Comment by Mbucari** [comment]
Ready!

This fixes #675, and I'm pretty sure it's also going to fix #676.

There wasn't a ticket about it, but add "fixed quick filters on startup in chardonnay"

(I posted this exact message by accident on the Dinah PR.)

**Comment by rmcrackan** [comment]
ffs how long have I been saying "for Windows" in the release notes ever since being x-plat?

**Pull request merged**
