### PR TITLE
Linux runners and Docker image

### PR DESCRIPTION
**Pull request by pixil98**
Fixes https://github.com/rmcrackan/Libation/issues/410, https://github.com/rmcrackan/Libation/issues/395

## Changes
* Refactored build workflows to use Linux runners for Linux and MacOS builds
  * Builds finish quicker
  * Executables are properly marked as executable
  * Linux and MacOS versions use gzip instead of zip in order to preserve permissions
* Build workflows get build version from AppScaffolding by default. Release workflow overrides version using the tag name.
* Pull requests and merges to main now run unit tests automatically on Linux and Windows.
* Docker image is now build and published automatically as part of release.
* Dependabot configuration to check github actions for updates.
* C# projects have been been updated to allow Linux to build Windows versions.
  * This is unused currently due to a bug in dotnet.

## Post merge
After merging this, you'll need to setup the following secrets for docker
* DOCKERHUB_USERNAME -- Your username, `rmcrackan1`
* DOCKERHUB_TOKEN -- A token you generate on docker's website. https://docs.docker.com/docker-hub/access-tokens/#create-an-access-token

## Example
Validate workflow: https://github.com/pixil98/Libation/actions/runs/3727173017
Release workflow: https://github.com/pixil98/Libation/actions/runs/3727147663
Release: https://github.com/pixil98/Libation/releases/tag/v9.0.16

### CODE REVIEW

**Comment by rmcrackan** [comment]
I added the DOCKERHUB_TOKEN secret. DOCKERHUB_USERNAME isn't really a secret. Where do you suggest adding it to github?

**Comment by rmcrackan** [comment]
Done

**Comment by rmcrackan** [comment]
Not that it should matter for your work -- just in case though:

I got docker to give me back control of my old rmcrackan. Secrets are updated. This is what I'll start using again and I'll abandon rmcrackan1

**Comment by pixil98** [comment]
That shouldn't matter, I set it up to base everything on the username secret so I can run the exact same workflow when testing and use my account. It would be good if you created the `libation` project in your account if you haven't already.

**Comment by rmcrackan** [comment]
libation docker repository created

**Comment by rmcrackan** [comment]
Gracias. What's the new release protocol? Do I still push a new tag to initiate publish?

**Comment by pixil98** [comment]
Exact same as before, push a tag in the format of `vX.Y.Z` and it will build all four configurations, create a draft release, and publish a docker image with the tagged version as well as marking it as `latest`.

**Comment by rmcrackan** [comment]
Thanks. I recall you'd said you were going to have your scripting compare it to app scaffolding. Is that just a sanity check?

**Comment by pixil98** [comment]
No, I didn't do a sanity check like I wanted. It was more complicated because you're not tagging it with the same version. It probably wouldn't be too hard to add at some point, but I didn't have the time to right now. For now, versions are used in the following ways:
* Pull requests and merges to main will build with the version in AppScaffolding.csproj
* Releases will build with the version from the tag name
* The release itself will use the version from the tag name
* Docker images will be created using the version from the tag name as well as being set to latest

**Pull request merged**
