### PR TITLE
Fix Character Replacements and Add More Useful Error Messages

### PR DESCRIPTION
**Pull request by Mbucari**
- Filename / path character replacements now work as expected on both Windows and Unix. Additionally, it's now a general file character replacement tool as requested in #357.
- Updated all tests to work on both Windows and Unix
- Add new fail states and log messages for `ContentLicenseDeniedException`. If the temporary denial of service is detected, launch a message box informing the user. #352 
- Added deleted books tab to Hangover. #409 

And ignore the Settings.Designer file. All I did was change the size of the "Edit how filename characters are replaced" button.

### CODE REVIEW

**Comment by rmcrackan** [comment]
Woah, this is a huge one. I bet those file path tests took a ton of work. I spent a few hours last night thinking I had an easy fix then woke up this morning to see why they wouldn't work so I reverted my local changes.

Can you look at the 'files changed' tab for this PR and ctrl+F `obsolete` ? The new build files have started to mark these. **If** they're low effort, can you fix them? If not -- if it ain't broke...

**Comment by Mbucari** [comment]
> I bet those file path tests took a ton of work. 

And about 1/4 of that work was figuring out how to debug tests on my Ubuntu VM, and 1/2 of the work was making character replacement work for both Windows and Unix!

> **If** they're low effort, can you fix them

All of the file dialog ones are pretty easy. The reason I haven't changed `WebRequest` (which was deprecated in 6.0) is because it has the `AddRange()` method built-in. But I'll see how much bother it is to change to `HttpClient`

**Comment by Mbucari** [comment]
Oh hey, did you see this?

https://github.com/rmcrackan/Libation/blob/19860e9f09e2416b303b6e86f386f549c8f947e4/Source/LibationFileManager/Configuration.Logging.cs#L18-L27

Now every file path will be logged once instead of 3 times!

**Comment by rmcrackan** [comment]
NIIIIIICE -- no I did not see this. Actually 4 times: Path, ShortPathName, LongPathName, PathWithoutPrefix. tbh, I've gotten so used to viewing paths in logs that way that I'd stopped questioning it. I prefer the PathWithoutPrefix since that's how I'm used to seeing it, but no complaints about this way either.

Now that I'm scrutinizing my old vs new logs I noticed something else. A few paths aren't longpaths (LibationFiles, InProgress). Obviously that's not a problem though or it would have bitten us by now.

**Pull request merged**
