### PR TITLE
Mp3 embedded cuesheet and raw metadata

### PR DESCRIPTION
**Pull request by Mbucari**
## [Add mp3 embedded cuesheet](https://github.com/rmcrackan/Libation/commit/3cf5fc1d996dec81380c0ea1c0dc44dfdd8db964) #667 

This also fixes a bug in Convert to Mp3 where the VBR tag was not being written.

## [Save raw json metadata](https://github.com/rmcrackan/Libation/commit/07eaa48e1052c03da0494d9d5e7480ca07810fca) #672

This will save metadata in [the form I showed in my example](https://github.com/rmcrackan/Libation/issues/672#issuecomment-1636829373).

### CODE REVIEW

**Comment by Mbucari** [comment]
Maybe hold off on making a new release for a few days. After the 10.6 rollout fiasco I'm a bit gun shy, and I'd like a little more time for more bugs from that release to filter in.

**Comment by CLHatch** [comment]
> Maybe hold off on making a new release for a few days. After the 10.6 rollout fiasco I'm a bit gun shy, and I'd like a little more time for more bugs from that release to filter in.

What?  It looked like you were having fun.  Totally wasn't stressful AT ALL. :)

**Comment by CLHatch** [comment]
> Maybe hold off on making a new release for a few days. After the 10.6 rollout fiasco I'm a bit gun shy, and I'd like a little more time for more bugs from that release to filter in.

Speaking of which, Just found another bug with auto-detecting existing books.  Issue incoming.

**Comment by rmcrackan** [comment]
> Maybe hold off on making a new release for a few days. After the 10.6 rollout fiasco I'm a bit gun shy, and I'd like a little more time for more bugs from that release to filter in.

Understood. This looks fine to me. Do you want me to merge now and release when I hear from you? Or also wait to merge this PR until then?

**Comment by Mbucari** [comment]
> Understood. This looks fine to me. Do you want me to merge now and release when I hear from you? Or also wait to merge this PR until then?

Go ahead and merge. I may have something else to add later, but let's try to keep these PRs smaller for your sake lol.

**Pull request merged**
