### PR TITLE
Bug fixes and performance improvements

### PR DESCRIPTION
**Pull request by Mbucari**
# [Fix bug where book with corrupt image cannot be queued.](https://github.com/rmcrackan/Libation/commit/5ec01913d51551d0328af41ea71f88fd03a5bf73)

More error handling for corrupted cover images.

# [Fix window restore maximize state on secondary monitor.](https://github.com/rmcrackan/Libation/commit/3f0e6b9ee5c60d415b34d36c085808e6d7652553)

Window position wasn't being restored when Libation was closed from maximized state on a second monitor.

# [Source/LibationAvalonia/ViewModels/ProductsDisplayViewModel.cs](https://github.com/rmcrackan/Libation/commit/eed42bd108d2103e267f7f6843f96378f272fb83#diff-a519b32b5936f9ef0982657ca883d6082f2fcd0567c37f8abfc7add084138972)

Use HashSet to reduce lookup time.

# [Use new AudibleApi methods](https://github.com/rmcrackan/Libation/commit/ec7dd1b54a4ffa6a3b55d7d9bcd3e32a2540291e)

- Write `DtoBase.SourceJson` to the zip archive.
- Redesigned ApiExtended so now all catalog get requests are performed in batches of 50. So Instead of doing one get for a podcast with 1 episode, that 1 episode's asin is added to the request queue and is only requested once the queue reaches 50 items.

### CODE REVIEW

**Comment by rmcrackan** [comment]
> Window position wasn't being restored when Libation was closed from maximized state on a second monitor.

Weird, this works on my rig. Thanks for finding this though. I never would have.

**Comment by rmcrackan** [comment]
> all catalog get requests are performed in batches of 50

Wow, that is impressively less code for better performance. Me likey

**Comment by Mbucari** [comment]
> > Window position wasn't being restored when Libation was closed from maximized state on a second monitor.
> 
> Weird, this works on my rig.

Are you on windows 10? I think it was working on my win10 machine but it wasn't on my new win11 machine.

**Comment by rmcrackan** [comment]
Yup: Win 10

**Pull request merged**
